"""
ORM models for:
  - Batch
  - BatchTrainer (many-to-many join table)
  - BatchStudent (many-to-many join table)
  - BatchInvite
  - SessionModel
  - Attendance
"""
from datetime import datetime, timezone
from sqlalchemy import (
    Column, Integer, String, Boolean, DateTime, Date, Time,
    ForeignKey, UniqueConstraint,
)
from sqlalchemy.orm import relationship
from src.db.database import Base


class Batch(Base):
    __tablename__ = "batches"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    institution_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    institution = relationship("User", foreign_keys=[institution_id])
    trainers = relationship("BatchTrainer", back_populates="batch", cascade="all, delete-orphan")
    students = relationship("BatchStudent", back_populates="batch", cascade="all, delete-orphan")
    invites = relationship("BatchInvite", back_populates="batch", cascade="all, delete-orphan")
    sessions = relationship("SessionModel", back_populates="batch", cascade="all, delete-orphan")


class BatchTrainer(Base):
    """Many-to-many: multiple trainers can be assigned to the same batch."""
    __tablename__ = "batch_trainers"
    __table_args__ = (UniqueConstraint("batch_id", "trainer_id"),)

    batch_id = Column(Integer, ForeignKey("batches.id", ondelete="CASCADE"), primary_key=True)
    trainer_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)

    batch = relationship("Batch", back_populates="trainers")
    trainer = relationship("User", foreign_keys=[trainer_id])


class BatchStudent(Base):
    """Many-to-many: students enrolled in batches."""
    __tablename__ = "batch_students"
    __table_args__ = (UniqueConstraint("batch_id", "student_id"),)

    batch_id = Column(Integer, ForeignKey("batches.id", ondelete="CASCADE"), primary_key=True)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), primary_key=True)

    batch = relationship("Batch", back_populates="students")
    student = relationship("User", foreign_keys=[student_id])


class BatchInvite(Base):
    """Invite tokens generated by trainers for students to join batches."""
    __tablename__ = "batch_invites"

    id = Column(Integer, primary_key=True, index=True)
    batch_id = Column(Integer, ForeignKey("batches.id", ondelete="CASCADE"), nullable=False)
    token = Column(String, unique=True, nullable=False, index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=False)
    expires_at = Column(DateTime, nullable=False)
    used = Column(Boolean, default=False, nullable=False)

    batch = relationship("Batch", back_populates="invites")
    creator = relationship("User", back_populates="invites_created", foreign_keys=[created_by])


class SessionModel(Base):
    """Training sessions created by trainers within a batch."""
    __tablename__ = "sessions"

    id = Column(Integer, primary_key=True, index=True)
    batch_id = Column(Integer, ForeignKey("batches.id", ondelete="CASCADE"), nullable=False)
    trainer_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    title = Column(String, nullable=False)
    date = Column(Date, nullable=False)
    start_time = Column(Time, nullable=False)
    end_time = Column(Time, nullable=False)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    batch = relationship("Batch", back_populates="sessions")
    trainer = relationship("User", back_populates="sessions_created", foreign_keys=[trainer_id])
    attendance_records = relationship(
        "Attendance", back_populates="session", cascade="all, delete-orphan"
    )


class Attendance(Base):
    """Attendance record per student per session."""
    __tablename__ = "attendance"
    __table_args__ = (UniqueConstraint("session_id", "student_id"),)

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(Integer, ForeignKey("sessions.id", ondelete="CASCADE"), nullable=False)
    student_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    # Status: present | absent | late
    status = Column(String, nullable=False)
    marked_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))

    session = relationship("SessionModel", back_populates="attendance_records")
    student = relationship("User", back_populates="attendance_records", foreign_keys=[student_id])
